/* =========================================================
   SUMATIF PLANNER - DATA MASTER
   Admin-only management workspace.
   ========================================================= */

(function () {
    const state = { profile: null, activeTab: "academic_years", tables: { academic_years: { label: "Tahun Pelajaran", columns: ["name"] }, classes: { label: "Kelas", columns: ["academic_year_id", "name", "level", "is_active"] }, subjects: { label: "Mata Pelajaran", columns: ["name", "short_name", "is_active"] }, profiles: { label: "Data Guru", columns: ["full_name", "role", "is_active"] } } };
    function isAdmin(){return state.profile&&state.profile.role==="admin";}
    function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
    function ensureMenu(){const nav=document.querySelector(".sidebar-nav");if(!nav||document.getElementById("masterDataMenu"))return;const d=document.createElement("div");d.className="sidebar-divider";d.id="masterDataDivider";const b=document.createElement("button");b.type="button";b.id="masterDataMenu";b.className="sidebar-menu";b.dataset.menu="master";b.innerHTML='<span class="sidebar-icon">▦</span><span>Data Master</span>';const p=nav.querySelector('[data-menu="profile"]');if(p){nav.insertBefore(d,p);nav.insertBefore(b,p);}else{nav.appendChild(d);nav.appendChild(b);}}
    function hideAllWorkspace(){document.querySelectorAll(".dashboard-home").forEach(el=>el.classList.add("hidden"));["scheduleWorkspace","calendarWorkspace","reportWorkspace","profileWorkspace","masterWorkspace"].forEach(id=>document.getElementById(id)?.classList.add("hidden"));}
    function setActive(menu){document.querySelectorAll(".sidebar-menu").forEach(b=>b.classList.toggle("active",b.dataset.menu===menu));}
    function showMaster(){if(!isAdmin()){showAppDialog("Anda tidak memiliki hak akses untuk Data Master.","warning","Akses Ditolak");return;}hideAllWorkspace();document.getElementById("masterWorkspace")?.classList.remove("hidden");setActive("master");loadTab(state.activeTab);}
    function injectWorkspace(){if(document.getElementById("masterWorkspace"))return;const main=document.querySelector(".app-content");if(!main)return;const s=document.createElement("section");s.id="masterWorkspace";s.className="master-workspace hidden";s.innerHTML='<div class="section-header"><div><h2>Data Master</h2><p>Kelola data dasar yang digunakan oleh Jadwal, Kalender, dan Laporan Sumatif.</p></div></div><div class="master-tabs" id="masterTabs"></div><div class="master-panel" id="masterPanel"><div class="master-loading">Memuat data...</div></div>';main.appendChild(s);renderTabs();}
    function renderTabs(){const t=document.getElementById("masterTabs");if(!t)return;t.innerHTML=Object.entries(state.tables).map(([k,v])=>`<button type="button" class="master-tab ${state.activeTab===k?"active":""}" data-master-tab="${k}">${v.label}</button>`).join("")+`<button type="button" class="master-tab ${state.activeTab==="education_calendar"?"active":""}" data-master-tab="education_calendar">Kalender Pendidikan</button><button type="button" class="master-tab disabled" title="Belum diaktifkan karena tabel students belum tersedia">Data Siswa</button>`;t.querySelectorAll("[data-master-tab]").forEach(b=>b.addEventListener("click",()=>loadTab(b.dataset.masterTab)));}
    async function loadTab(tab){state.activeTab=tab;renderTabs();const p=document.getElementById("masterPanel");if(!p)return;p.innerHTML='<div class="master-loading">Memuat data...</div>';if(tab==="education_calendar"){await loadCalendar(p);return;}const c=state.tables[tab];if(!c)return;let q=supabaseClient.from(tab).select("*");if(tab==="profiles")q=q.eq("role","guru").order("full_name");else if(tab==="classes")q=q.order("name");else q=q.order(c.columns[0]);const {data,error}=await q;if(error){p.innerHTML=`<div class="master-error">Gagal memuat ${esc(c.label)}: ${esc(error.message)}</div>`;return;}renderTable(p,tab,c,data||[]);}
    async function getAcademicYears(){const {data,error}=await supabaseClient.from("academic_years").select("id,name,start_date,end_date,is_active").order("start_date",{ascending:false});if(error)throw error;return data||[];}
    async function renderClasses(panel,rows){let years=[];try{years=await getAcademicYears();}catch(e){panel.innerHTML=`<div class="master-error">Gagal memuat Tahun Pelajaran: ${esc(e.message)}</div>`;return;}const ym=Object.fromEntries(years.map(y=>[y.id,y.name]));panel.innerHTML=`<div class="master-panel-header"><div><h3>Kelas</h3><span>${rows.length} data</span></div><button type="button" class="primary-button" id="masterAddButton">+ Tambah Data</button></div><div class="master-table-wrap"><table class="master-table"><thead><tr><th>Tahun Pelajaran</th><th>Nama Kelas</th><th>Tingkat</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${esc(ym[r.academic_year_id]||"-")}</td><td>${esc(r.name)}</td><td>${esc(r.level)}</td><td><span class="master-status ${r.is_active?"active":"inactive"}">${r.is_active?"Aktif":"Tidak Aktif"}</span></td><td class="master-actions"><button type="button" class="master-action edit" data-master-edit="${esc(r.id)}">Edit</button><button type="button" class="master-action status" data-master-toggle="${esc(r.id)}">${r.is_active?"Nonaktifkan":"Aktifkan"}</button><button type="button" class="master-action delete" data-master-delete="${esc(r.id)}">Hapus</button></td></tr>`).join(""): '<tr><td colspan="5" class="master-empty">Belum ada data.</td></tr>'}</tbody></table></div>`;panel.querySelector("#masterAddButton")?.addEventListener("click",()=>openClassForm(null,years));panel.querySelectorAll("[data-master-edit]").forEach(b=>b.addEventListener("click",()=>openClassForm(rows.find(x=>x.id===b.dataset.masterEdit)||null,years)));panel.querySelectorAll("[data-master-toggle]").forEach(b=>b.addEventListener("click",()=>{const r=rows.find(x=>x.id===b.dataset.masterToggle);if(r)toggleClassStatus(r);}));panel.querySelectorAll("[data-master-delete]").forEach(b=>b.addEventListener("click",()=>deleteRow("classes",b.dataset.masterDelete)));}
    function renderTable(panel,tab,config,rows){if(tab==="classes"){renderClasses(panel,rows);return;}const labels={name:"Nama",level:"Tingkat",short_name:"Singkatan",full_name:"Nama Guru",role:"Peran",is_active:"Status"};const headers=config.columns.map(c=>`<th>${labels[c]||c}</th>`).join("");const body=rows.length?rows.map(r=>`<tr>${config.columns.map(c=>`<td>${c==="is_active"?`<span class="master-status ${r[c]?"active":"inactive"}">${r[c]?"Aktif":"Tidak Aktif"}</span>`:esc(r[c])}</td>`).join("")}<td class="master-actions"><button type="button" class="master-action edit" data-master-edit="${esc(r.id)}">Edit</button>${config.columns.includes("is_active")?`<button type="button" class="master-action status" data-master-toggle="${esc(r.id)}">${r.is_active?"Nonaktifkan":"Aktifkan"}</button>`:""}<button type="button" class="master-action delete" data-master-delete="${esc(r.id)}">Hapus</button></td></tr>`).join(""): `<tr><td colspan="${config.columns.length+1}" class="master-empty">Belum ada data.</td></tr>`;panel.innerHTML=`<div class="master-panel-header"><div><h3>${config.label}</h3><span>${rows.length} data</span></div><button type="button" class="primary-button" id="masterAddButton">+ Tambah Data</button></div><div class="master-table-wrap"><table class="master-table"><thead><tr>${headers}<th>Aksi</th></tr></thead><tbody>${body}</tbody></table></div>`;panel.querySelector("#masterAddButton")?.addEventListener("click",()=>openForm(tab,config,null));panel.querySelectorAll("[data-master-edit]").forEach(b=>b.addEventListener("click",()=>{const r=rows.find(x=>x.id===b.dataset.masterEdit);openForm(tab,config,r||null);}));panel.querySelectorAll("[data-master-toggle]").forEach(b=>b.addEventListener("click",()=>toggleStatus(tab,rows.find(x=>x.id===b.dataset.masterToggle))));panel.querySelectorAll("[data-master-delete]").forEach(b=>b.addEventListener("click",()=>deleteRow(tab,b.dataset.masterDelete)));}
    async function toggleStatus(tab,row){if(!row)return;const next=!row.is_active;const label=tab==="subjects"?`mata pelajaran ${row.name}`:`data ${row.full_name||row.name||"ini"}`;if(!confirm(`Yakin ingin ${next?"mengaktifkan":"menonaktifkan"} ${label}?`))return;const {error}=await supabaseClient.from(tab).update({is_active:next}).eq("id",row.id);if(error){showAppDialog(error.message||"Gagal mengubah status.","error","Gagal Mengubah Status");return;}await loadTab(tab);showAppDialog(`${tab==="subjects"?"Mata pelajaran":"Data"} ${row.name||row.full_name} berhasil ${next?"diaktifkan":"dinonaktifkan"}.`,"success","Status Diperbarui");}
    async function toggleClassStatus(row){const next=!row.is_active;if(!confirm(`Yakin ingin ${next?"mengaktifkan":"menonaktifkan"} kelas ${row.name}?`))return;const {error}=await supabaseClient.from("classes").update({is_active:next}).eq("id",row.id);if(error){showAppDialog(error.message||"Gagal mengubah status.","error","Gagal Mengubah Status");return;}await loadTab("classes");showAppDialog(`Kelas ${row.name} berhasil ${next?"diaktifkan":"dinonaktifkan"}.`,"success","Status Kelas");}
    function openForm(tab,config,row){const fields=config.columns.map(c=>{if(c==="is_active")return `<label><input type="checkbox" name="${c}" ${row?.[c]!==false?"checked":""}> Aktif</label>`;return `<label>${c==="name"?"Nama":"Singkatan"}<input name="${c}" value="${esc(row?.[c])}" required></label>`;}).join("");showMasterModal(`${row?"Edit":"Tambah"} ${config.label}`,fields,async form=>{const payload={};config.columns.forEach(c=>payload[c]=c==="is_active"?form.elements[c].checked:form.elements[c].value.trim());await saveRow(tab,row?.id,payload);});}
    function openClassForm(row,years){const opts=years.filter(y=>y.is_active||y.id===row?.academic_year_id).map(y=>`<option value="${esc(y.id)}" ${y.id===row?.academic_year_id?"selected":""}>${esc(y.name)}</option>`).join("")||'<option value="">Belum ada Tahun Pelajaran aktif</option>';const fields=`<label>Tahun Pelajaran<select name="academic_year_id" required>${opts}</select></label><label>Nama Kelas<input name="name" value="${esc(row?.name)}" placeholder="Contoh: 5A" required></label><label>Tingkat<select name="level" required>${[1,2,3,4,5,6].map(l=>`<option value="${l}" ${Number(row?.level)===l?"selected":""}>${l}</option>`).join("")}</select></label><label><input type="checkbox" name="is_active" ${row?.id?(row.is_active?"checked":""):"checked"}> Aktif</label>`;showMasterModal(`${row?"Edit":"Tambah"} Kelas`,fields,async form=>{await saveRow("classes",row?.id,{academic_year_id:form.elements.academic_year_id.value,name:form.elements.name.value.trim(),level:Number(form.elements.level.value),is_active:form.elements.is_active.checked});});}
    async function loadCalendar(panel){const {data,error}=await supabaseClient.from("education_calendar").select("*").order("date");if(error){panel.innerHTML=`<div class="master-error">Gagal memuat Kalender Pendidikan: ${esc(error.message)}</div>`;return;}const rows=data||[];panel.innerHTML=`<div class="master-panel-header"><div><h3>Kalender Pendidikan</h3><span>${rows.length} data</span></div><button type="button" class="primary-button" id="masterCalendarAdd">+ Tambah Event</button></div><div class="master-table-wrap"><table class="master-table"><thead><tr><th>Tanggal</th><th>Semester</th><th>Jenis</th><th>Judul</th><th>Dapat Dipilih</th><th>Aksi</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${r.semester===1?"Ganjil":"Genap"}</td><td>${esc(r.day_type)}</td><td>${esc(r.title)}</td><td>${r.is_selectable?"Ya":"Tidak"}</td><td class="master-actions"><button class="master-action edit" data-cal-edit="${esc(r.id)}">Edit</button><button class="master-action delete" data-cal-delete="${esc(r.id)}">Hapus</button></td></tr>`).join(""):'<tr><td colspan="6" class="master-empty">Belum ada event.</td></tr>'}</tbody></table></div>`;panel.querySelector("#masterCalendarAdd")?.addEventListener("click",()=>openCalendarForm(null));panel.querySelectorAll("[data-cal-edit]").forEach(b=>b.addEventListener("click",()=>openCalendarForm(rows.find(x=>x.id===b.dataset.calEdit))));panel.querySelectorAll("[data-cal-delete]").forEach(b=>b.addEventListener("click",()=>deleteRow("education_calendar",b.dataset.calDelete)));}
    function showMasterModal(title,fields,onSubmit){document.getElementById("masterModalOverlay")?.remove();const o=document.createElement("div");o.id="masterModalOverlay";o.className="master-modal-overlay";o.innerHTML=`<div class="master-modal"><h3>${esc(title)}</h3><form id="masterForm">${fields}<div class="master-modal-actions"><button type="button" class="secondary-button" id="masterCancel">Batal</button><button type="submit" class="primary-button">Simpan</button></div></form></div>`;document.body.appendChild(o);o.querySelector("#masterCancel").onclick=()=>o.remove();o.querySelector("form").onsubmit=async e=>{e.preventDefault();const b=o.querySelector('[type="submit"]');b.disabled=true;try{await onSubmit(e.target);o.remove();await loadTab(state.activeTab);}catch(err){showAppDialog(err.message||"Gagal menyimpan data.","error","Gagal Menyimpan");b.disabled=false;}};}
    async function saveRow(tab,id,payload){const q=id?supabaseClient.from(tab).update(payload).eq("id",id):supabaseClient.from(tab).insert(payload);const {error}=await q;if(error)throw error;}
    function openCalendarForm(row){const f=`<label>Tanggal<input type="date" name="date" value="${esc(row?.date)}" required></label><label>Semester<select name="semester"><option value="1" ${row?.semester!==2?"selected":""}>Ganjil</option><option value="2" ${row?.semester===2?"selected":""}>Genap</option></select></label><label>Jenis<input name="day_type" value="${esc(row?.day_type||"Hari Efektif")}" required></label><label>Judul<input name="title" value="${esc(row?.title)}" required></label><label>Deskripsi<textarea name="description">${esc(row?.description)}</textarea></label><label><input type="checkbox" name="is_selectable" ${row?.id?(row.is_selectable?"checked":""):"checked"}> Dapat Dipilih</label>`;showMasterModal(`${row?"Edit":"Tambah"} Event Kalender Pendidikan`,f,async form=>{await saveRow("education_calendar",row?.id,{date:form.elements.date.value,semester:Number(form.elements.semester.value),day_type:form.elements.day_type.value.trim(),title:form.elements.title.value.trim(),description:form.elements.description.value.trim(),is_selectable:form.elements.is_selectable.checked});});}
    async function deleteRow(tab,id){if(!confirm("Yakin ingin menghapus data ini?"))return;const {error}=await supabaseClient.from(tab).delete().eq("id",id);if(error){showAppDialog(error.message||"Gagal menghapus data.","error","Gagal Menghapus");return;}await loadTab(state.activeTab);}
    function boot(profile){if(profile)state.profile=profile;if(!isAdmin())return;ensureMenu();injectWorkspace();const b=document.getElementById("masterDataMenu");if(b&&!b.dataset.bound){b.dataset.bound="1";b.addEventListener("click",showMaster);}console.log("[Master] Data Master admin aktif.");}
    window.initMaster=boot;
})();